name: get
on:
  schedule:
    - cron: '0 0 * * 0'
  push:
    branches:
      - master

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: |
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://akilar.top/ -o akilar.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.nesxc.com/ -o nesxc.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.itciraos.cn/ -o www.itciraos.cn.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://android99.me -o android99.me.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.zhheo.com/ -o blog.zhheo.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://zfe.space/ -o zfe.space.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://noionion.top/ -o noionion.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.heyiki.top -o www.heyiki.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.iftiger.com/ -o www.iftiger.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://bili33.top/ -o bili33.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://wxydejoy.top -o wxydejoy.top.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.imlazy.ink:233/ -o blog.imlazy.ink:233.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://blog.ccknbc.cc -o blog.ccknbc.cc.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://www.godlucas.club/ -o www.godlucas.clubc.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/http://blog.xn--2br199bf9h.com/ blog.xn--2br199bf9h.com.jpg
        curl https://image.thum.io/get/width/400/crop/800/allowJPG/wait/20/noanimate/https://ranas.cn/ -o ranas.cn.jpg
        curl https://purge.jsdelivr.net/gh/HopeLight/ScreenShot@gh-pages/*.*
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN }}
        publish_dir: ./
